# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f9ee994c0f517fdde82cf07b5ed5013a"
name = "MP Suscripciones"
application_url = "https://YOUR-APP.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,write_draft_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://YOUR-APP.up.railway.app/auth/callback",
  "https://YOUR-APP.up.railway.app/auth/shopify/callback",
  "https://YOUR-APP.up.railway.app/api/auth"
]
